# Load and Explore

In [1]:
import pandas as pd

In [2]:
# 12.20
sales = pd.read_csv('sales_dashboard.csv')

In [3]:
sales

,Date,Region,Salesperson,Product,Category,Units Sold,Revenue
0,2026-01-01,West,John,Laptop,Electronics,2,500000
1,2026-01-01,East,Sarah,Mouse,Accessories,10,30000
2,2026-01-02,West,John,Keyboard,Accessories,5,40000
3,2026-01-02,North,Mike,Laptop,Electronics,1,250000
4,2026-01-03,South,Emma,Monitor,Electronics,2,100000
5,2026-01-03,East,Sarah,Headphones,Accessories,3,36000
6,2026-01-04,West,John,Monitor,Electronics,1,50000
7,2026-01-04,North,Mike,Mouse,Accessories,8,24000
8,2026-01-05,South,Emma,Laptop,Electronics,1,250000
9,2026-01-05,East,Sarah,Keyboard,Accessories,4,32000
10,2026-01-06,West,John,Headphones,Accessories,2,24000
11,2026-01-06,North,Mike,Monitor,Electronics,1,50000

In [4]:
sales.columns

Index(['Date', 'Region', 'Salesperson', 'Product', 'Category', 'Units Sold',
       'Revenue'],
      dtype='str')

In [5]:
sales.dtypes

Date             str
Region           str
Salesperson      str
Product          str
Category         str
Units Sold     int64
Revenue        int64
dtype: object

In [6]:
sales.shape

(12, 7)

In [7]:
sales.info()

<class 'pandas.DataFrame'>
RangeIndex: 12 entries, 0 to 11
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Date         12 non-null     str
 1   Region       12 non-null     str
 2   Salesperson  12 non-null     str
 3   Product      12 non-null     str
 4   Category     12 non-null     str
 5   Units Sold   12 non-null     int64
 6   Revenue      12 non-null     int64
dtypes: int64(2), str(5)
memory usage: 804.0 bytes

In [8]:
sales.describe()

       Units Sold        Revenue
count   12.000000      12.000000
mean     3.333333  115500.000000
std      2.964436  146439.252065
min      1.000000   24000.000000
25%      1.000000   31500.000000
50%      2.000000   45000.000000
75%      4.250000  137500.000000
max     10.000000  500000.000000

# Traditional GroupBy

- Find revenue by region:

In [9]:
sales.groupby('Region')['Revenue'].sum()

Region
East      98000
North    324000
South    350000
West     614000
Name: Revenue, dtype: int64

- Find revenue by salesperson:

In [10]:
sales.groupby('Salesperson')['Revenue'].sum()

Salesperson
Emma     350000
John     614000
Mike     324000
Sarah     98000
Name: Revenue, dtype: int64

# Pivot Table

In [11]:
pd.pivot_table(sales, index='Region', values='Revenue', aggfunc='sum')

        Revenue
Region
East      98000
North    324000
South    350000
West     614000

In [46]:
region_revenue = pd.pivot_table(sales, index='Region', values='Revenue', aggfunc='sum')

In [47]:
region_revenue.sort_values(by='Revenue',ascending=False)

        Revenue
Region
West     614000
South    350000
North    324000
East      98000

Which region generated the highest revenue? West

In [12]:
pd.pivot_table(sales, index='Salesperson', values='Revenue', aggfunc='sum')

             Revenue
Salesperson
Emma          350000
John          614000
Mike          324000
Sarah          98000

# Region vs Category

In [13]:
pd.pivot_table(sales, index='Region', columns='Category', values='Revenue', aggfunc='sum')

Category  Accessories  Electronics
Region
East          98000.0          NaN
North         24000.0     300000.0
South             NaN     350000.0
West          64000.0     550000.0

# Salesperson Dashboard

In [15]:
pd.pivot_table(sales,index='Salesperson',values=['Revenue','Units Sold'],aggfunc='sum')

             Revenue  Units Sold
Salesperson
Emma          350000           3
John          614000          10
Mike          324000          10
Sarah          98000          17

- Who generated the highest revenue? John
- Who sold the most units? John and Mike

# Product Dashboard

In [16]:
pd.pivot_table(sales,index='Product',values=['Units Sold', 'Revenue'], aggfunc='sum')

            Revenue  Units Sold
Product
Headphones    60000           5
Keyboard      72000           9
Laptop      1000000           4
Monitor      200000           4
Mouse         54000          18

- Best product by revenue? laptop
- Best product by units sold? Mouse

# Multiple Dimensions

In [44]:
pd.pivot_table(sales,index='Region',columns='Product',values='Revenue',aggfunc='sum',fill_value=0)

Product  Headphones  Keyboard  Laptop  Monitor  Mouse
Region
East          36000     32000       0        0  30000
North             0         0  250000    50000  24000
South             0         0  250000   100000      0
West          24000     40000  500000    50000      0

# Multiple Aggregations

In [ ]:
pd.pivot_table(sales,index='Region',columns='Category',values='Revenue',aggfunc=['sum','mean','max'],fill_value=0)

                 sum                      mean                     max  \
Category Accessories Electronics   Accessories Electronics Accessories
Region
East           98000           0  32666.666667         0.0       36000
North          24000      300000  24000.000000    150000.0       24000
South              0      350000      0.000000    175000.0           0
West           64000      550000  32000.000000    275000.0       40000


Category Electronics
Region
East               0
North         250000
South         250000
West          500000

# Crosstab
A crosstab counts occurrences.

In [24]:
pd.crosstab(sales['Region'],sales['Category'])

Category  Accessories  Electronics
Region
East                3            0
North               1            2
South               0            2
West                2            2

- Which region sold more Electronics products? North,South and West
- Which region had more Accessories transactions? East

# Advanced Crosstab

In [26]:
pd.crosstab(sales['Salesperson'],sales['Category'])

Category     Accessories  Electronics
Salesperson
Emma                   0            2
John                   2            2
Mike                   1            2
Sarah                  3            0

# Add Margins

In [28]:
pd.pivot_table(sales,index='Region',columns='Category',values='Revenue',aggfunc='sum',fill_value=0,margins=True)

Category  Accessories  Electronics      All
Region
East            98000            0    98000
North           24000       300000   324000
South               0       350000   350000
West            64000       550000   614000
All            186000      1200000  1386000

# Covert Date

In [29]:
sales['Date']

0     2026-01-01
1     2026-01-01
2     2026-01-02
3     2026-01-02
4     2026-01-03
5     2026-01-03
6     2026-01-04
7     2026-01-04
8     2026-01-05
9     2026-01-05
10    2026-01-06
11    2026-01-06
Name: Date, dtype: str

In [30]:
sales['Date'] = pd.to_datetime(sales['Date'])

In [33]:
sales['Date']

0    2026-01-01
1    2026-01-01
2    2026-01-02
3    2026-01-02
4    2026-01-03
5    2026-01-03
6    2026-01-04
7    2026-01-04
8    2026-01-05
9    2026-01-05
10   2026-01-06
11   2026-01-06
Name: Date, dtype: datetime64[us]

In [34]:
sales['Month'] = sales['Date'].dt.month

In [35]:
sales

,Date,Region,Salesperson,Product,Category,Units Sold,Revenue,Month
0,2026-01-01,West,John,Laptop,Electronics,2,500000,1
1,2026-01-01,East,Sarah,Mouse,Accessories,10,30000,1
2,2026-01-02,West,John,Keyboard,Accessories,5,40000,1
3,2026-01-02,North,Mike,Laptop,Electronics,1,250000,1
4,2026-01-03,South,Emma,Monitor,Electronics,2,100000,1
5,2026-01-03,East,Sarah,Headphones,Accessories,3,36000,1
6,2026-01-04,West,John,Monitor,Electronics,1,50000,1
7,2026-01-04,North,Mike,Mouse,Accessories,8,24000,1
8,2026-01-05,South,Emma,Laptop,Electronics,1,250000,1
9,2026-01-05,East,Sarah,Keyboard,Accessories,4,32000,1
10,2026-01-06,West,John,Headphones,Accessories,2,24000,1
11,2026-01-06,North,Mike,Monitor,Electronics,1,50000,1

In [36]:
pd.pivot_table(sales, index='Month',values='Revenue',aggfunc='sum')

       Revenue
Month
1      1386000

# Export

In [37]:
dashboard1 = pd.pivot_table(sales,index='Salesperson',values=['Revenue','Units Sold'],aggfunc='sum')

In [38]:
dashboard1.to_csv('dashborad1.csv')

In [39]:
dashboard2 = pd.pivot_table(sales,index='Product',values=['Revenue','Units Sold'],aggfunc='sum')

In [40]:
dashboard2.to_csv('dashborad2.csv')

In [41]:
dashboard3 = pd.pivot_table(sales,index='Region',columns='Category',values='Revenue',aggfunc='sum',fill_value=0)

In [42]:
dashboard3.to_csv('dashborad3.csv')