In [1]:
import pandas as pd

# Data Exploration

In [2]:
review = pd.read_csv('googleplaystore_user_reviews.csv')

In [3]:
review.head()

,App,Translated_Review,Sentiment,Sentiment_Polarity,Sentiment_Subjectivity
0,10 Best Foods for You,I like eat delicious food. That's I'm cooking ...,Positive,1.00,0.533333
1,10 Best Foods for You,This help eating healthy exercise regular basis,Positive,0.25,0.288462
2,10 Best Foods for You,NaN,NaN,NaN,NaN
3,10 Best Foods for You,Works great especially going grocery store,Positive,0.40,0.875000
4,10 Best Foods for You,Best idea us,Positive,1.00,0.300000

In [4]:
playstore = pd.read_csv('googleplaystore.csv')

In [5]:
playstore.head()

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159,19M,"10,000+",Free,0,Everyone,Art & Design,"January 7, 2018",1.0.0,4.0.3 and up
1,Coloring book moana,ART_AND_DESIGN,3.9,967,14M,"500,000+",Free,0,Everyone,Art & Design;Pretend Play,"January 15, 2018",2.0.0,4.0.3 and up
2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,4.7,87510,8.7M,"5,000,000+",Free,0,Everyone,Art & Design,"August 1, 2018",1.2.4,4.0.3 and up
3,Sketch - Draw & Paint,ART_AND_DESIGN,4.5,215644,25M,"50,000,000+",Free,0,Teen,Art & Design,"June 8, 2018",Varies with device,4.2 and up
4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,4.3,967,2.8M,"100,000+",Free,0,Everyone,Art & Design;Creativity,"June 20, 2018",1.1,4.4 and up

In [6]:
review.shape

(64295, 5)

In [7]:
playstore.shape

(10841, 13)

In [8]:
review.info()

<class 'pandas.DataFrame'>
RangeIndex: 64295 entries, 0 to 64294
Data columns (total 5 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   App                     64295 non-null  str
 1   Translated_Review       37427 non-null  str
 2   Sentiment               37432 non-null  str
 3   Sentiment_Polarity      37432 non-null  float64
 4   Sentiment_Subjectivity  37432 non-null  float64
dtypes: float64(2), str(3)
memory usage: 2.5 MB

In [9]:
playstore.info()

<class 'pandas.DataFrame'>
RangeIndex: 10841 entries, 0 to 10840
Data columns (total 13 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   App             10841 non-null  str
 1   Category        10841 non-null  str
 2   Rating          9367 non-null   float64
 3   Reviews         10841 non-null  str
 4   Size            10841 non-null  str
 5   Installs        10841 non-null  str
 6   Type            10840 non-null  str
 7   Price           10841 non-null  str
 8   Content Rating  10840 non-null  str
 9   Genres          10841 non-null  str
 10  Last Updated    10841 non-null  str
 11  Current Ver     10833 non-null  str
 12  Android Ver     10838 non-null  str
dtypes: float64(1), str(12)
memory usage: 1.1 MB

In [10]:
review.columns

Index(['App', 'Translated_Review', 'Sentiment', 'Sentiment_Polarity',
       'Sentiment_Subjectivity'],
      dtype='str')

In [11]:
playstore.columns

Index(['App', 'Category', 'Rating', 'Reviews', 'Size', 'Installs', 'Type',
       'Price', 'Content Rating', 'Genres', 'Last Updated', 'Current Ver',
       'Android Ver'],
      dtype='str')

In [12]:
review.describe()

       Sentiment_Polarity  Sentiment_Subjectivity
count        37432.000000            37432.000000
mean             0.182146                0.492704
std              0.351301                0.259949
min             -1.000000                0.000000
25%              0.000000                0.357143
50%              0.150000                0.514286
75%              0.400000                0.650000
max              1.000000                1.000000

In [13]:
playstore.describe()

            Rating
count  9367.000000
mean      4.193338
std       0.537431
min       1.000000
25%       4.000000
50%       4.300000
75%       4.500000
max      19.000000

# Handle Missing

The maximum rating is 19.0, which is outside the valid rating range (1–5). This indicates a data quality issue and the row should be examined before calculating statistics such as the mean or filling missing values.

In [14]:
playstore[playstore['Rating'] > 5]

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
10472,Life Made WI-Fi Touchscreen Photo Frame,1.9,19.0,3.0M,"1,000+",Free,0,Everyone,NaN,"February 11, 2018",1.0.19,4.0 and up,NaN

In [15]:
playstore.iloc[1]

App                     Coloring book moana
Category                     ART_AND_DESIGN
Rating                                  3.9
Reviews                                 967
Size                                    14M
Installs                           500,000+
Type                                   Free
Price                                     0
Content Rating                     Everyone
Genres            Art & Design;Pretend Play
Last Updated               January 15, 2018
Current Ver                           2.0.0
Android Ver                    4.0.3 and up
Name: 1, dtype: object

**Data Quality Issue**

An invalid record was identified where the columns were shifted, causing incorrect values such as:

- Category = 1.9
- Rating = 19.0

Since Google Play Store ratings must be between 1 and 5 and categories should contain text values, this row was determined to be corrupted and was removed from the dataset before further analysis.

In [16]:
playstore = playstore.drop(10472)

In [17]:
playstore.describe()

            Rating
count  9366.000000
mean      4.191757
std       0.515219
min       1.000000
25%       4.000000
50%       4.300000
75%       4.500000
max       5.000000

In [18]:
playstore.isna().sum()

App                  0
Category             0
Rating            1474
Reviews              0
Size                 0
Installs             0
Type                 1
Price                0
Content Rating       0
Genres               0
Last Updated         0
Current Ver          8
Android Ver          2
dtype: int64

In [19]:
playstore['Type'].value_counts()

Type
Free    10039
Paid      800
Name: count, dtype: int64

In [20]:
playstore[playstore['Type'].isna() == True]

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
9148,Command & Conquer: Rivals,FAMILY,NaN,0,Varies with device,0,NaN,0,Everyone 10+,Strategy,"June 28, 2018",Varies with device,Varies with device

In [21]:
playstore = playstore.dropna(subset=['Type', 'Current Ver', 'Android Ver'])

In [22]:
playstore.isna().sum()

App                  0
Category             0
Rating            1469
Reviews              0
Size                 0
Installs             0
Type                 0
Price                0
Content Rating       0
Genres               0
Last Updated         0
Current Ver          0
Android Ver          0
dtype: int64

In [23]:
playstore.shape

(10829, 13)

In [24]:
playstore['Rating'] = playstore['Rating'].fillna(playstore['Rating'].mean())

In [25]:
playstore.isna().sum()

App               0
Category          0
Rating            0
Reviews           0
Size              0
Installs          0
Type              0
Price             0
Content Rating    0
Genres            0
Last Updated      0
Current Ver       0
Android Ver       0
dtype: int64

In [26]:
playstore.head()

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159,19M,"10,000+",Free,0,Everyone,Art & Design,"January 7, 2018",1.0.0,4.0.3 and up
1,Coloring book moana,ART_AND_DESIGN,3.9,967,14M,"500,000+",Free,0,Everyone,Art & Design;Pretend Play,"January 15, 2018",2.0.0,4.0.3 and up
2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,4.7,87510,8.7M,"5,000,000+",Free,0,Everyone,Art & Design,"August 1, 2018",1.2.4,4.0.3 and up
3,Sketch - Draw & Paint,ART_AND_DESIGN,4.5,215644,25M,"50,000,000+",Free,0,Teen,Art & Design,"June 8, 2018",Varies with device,4.2 and up
4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,4.3,967,2.8M,"100,000+",Free,0,Everyone,Art & Design;Creativity,"June 20, 2018",1.1,4.4 and up

In [27]:
playstore.dtypes

App                   str
Category              str
Rating            float64
Reviews               str
Size                  str
Installs              str
Type                  str
Price                 str
Content Rating        str
Genres                str
Last Updated          str
Current Ver           str
Android Ver           str
dtype: object

Now let's do the convertions

# Data Cleaning


##### Installs column str -> int

In [33]:
playstore['Installs'].str.endswith('+').sum()

np.int64(10829)

In [34]:
playstore.shape

(10829, 13)

In [35]:
playstore['Installs_clean'] = playstore['Installs'].str.replace("+","")

In [36]:
playstore.head()

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver,Installs_clean
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159,19M,"10,000+",Free,0,Everyone,Art & Design,"January 7, 2018",1.0.0,4.0.3 and up,"10,000"
1,Coloring book moana,ART_AND_DESIGN,3.9,967,14M,"500,000+",Free,0,Everyone,Art & Design;Pretend Play,"January 15, 2018",2.0.0,4.0.3 and up,"500,000"
2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,4.7,87510,8.7M,"5,000,000+",Free,0,Everyone,Art & Design,"August 1, 2018",1.2.4,4.0.3 and up,"5,000,000"
3,Sketch - Draw & Paint,ART_AND_DESIGN,4.5,215644,25M,"50,000,000+",Free,0,Teen,Art & Design,"June 8, 2018",Varies with device,4.2 and up,"50,000,000"
4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,4.3,967,2.8M,"100,000+",Free,0,Everyone,Art & Design;Creativity,"June 20, 2018",1.1,4.4 and up,"100,000"

In [38]:
playstore['Installs_clean'] = playstore['Installs_clean'].str.replace(",","")

In [39]:
playstore.head()

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver,Installs_clean
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159,19M,"10,000+",Free,0,Everyone,Art & Design,"January 7, 2018",1.0.0,4.0.3 and up,10000
1,Coloring book moana,ART_AND_DESIGN,3.9,967,14M,"500,000+",Free,0,Everyone,Art & Design;Pretend Play,"January 15, 2018",2.0.0,4.0.3 and up,500000
2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,4.7,87510,8.7M,"5,000,000+",Free,0,Everyone,Art & Design,"August 1, 2018",1.2.4,4.0.3 and up,5000000
3,Sketch - Draw & Paint,ART_AND_DESIGN,4.5,215644,25M,"50,000,000+",Free,0,Teen,Art & Design,"June 8, 2018",Varies with device,4.2 and up,50000000
4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,4.3,967,2.8M,"100,000+",Free,0,Everyone,Art & Design;Creativity,"June 20, 2018",1.1,4.4 and up,100000

In [40]:
playstore['Installs_clean'] = playstore['Installs_clean'].astype(int)

In [41]:
playstore.dtypes

App                   str
Category              str
Rating            float64
Reviews               str
Size                  str
Installs              str
Type                  str
Price                 str
Content Rating        str
Genres                str
Last Updated          str
Current Ver           str
Android Ver           str
Installs_clean      int64
dtype: object

##### Size column str -> int

In [43]:
playstore['Size'].str.endswith('M').sum()

np.int64(8823)

In [47]:
playstore['Size'].str.endswith('k').sum()

np.int64(312)

In [55]:
print(8823  + 312)

9135

In [50]:
playstore.shape

(10829, 14)

In [51]:
playstore.sample(10)

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver,Installs_clean
3226,Scout GPS Navigation & Meet Up,TRAVEL_AND_LOCAL,4.200000,120373,31M,"5,000,000+",Free,0,Everyone,Travel & Local,"July 31, 2018",3.19.35.999,4.0.3 and up,5000000
10443,Signal Info,TOOLS,4.600000,424,3.5M,"10,000+",Free,0,Everyone,Tools,"December 19, 2017",0.11,6.0 and up,10000
9961,Light Meter - EV,PHOTOGRAPHY,4.000000,26,8.5M,"1,000+",Free,0,Everyone,Photography,"August 2, 2018",4.1.1,4.4 and up,1000
4246,I LOVE PASTA,FAMILY,4.000000,83875,43M,"1,000,000+",Free,0,Everyone,Simulation,"September 8, 2017",1.6.1,2.3.3 and up,1000000
3436,Apex Launcher,PERSONALIZATION,4.300000,266402,Varies with device,"10,000,000+",Free,0,Everyone,Personalization,"August 4, 2018",Varies with device,Varies with device,10000000
2152,LEGO® Friends,FAMILY,4.400000,854,6.9M,"10,000+",Paid,$4.99,Everyone,Casual;Pretend Play,"December 1, 2015",Varies with device,4.0.3 and up,10000
4139,F Length Sim (no Ads),PHOTOGRAPHY,4.191838,0,1.7M,10+,Paid,$2.00,Everyone,Photography,"April 29, 2018",1.0,4.0.3 and up,10
8091,CY Konum,PERSONALIZATION,4.191838,1,1.3M,100+,Free,0,Everyone,Personalization,"June 27, 2018",3.0,5.1 and up,100
6587,Blood Pressure Log - MyDiary,MEDICAL,4.700000,8347,2.6M,"500,000+",Free,0,Everyone,Medical,"April 13, 2018",1.4.6,4.0 and up,500000
3167,Find Dining Restaurant Finder,TRAVEL_AND_LOCAL,4.100000,427,26M,"100,000+",Free,0,Everyone,Travel & Local,"March 21, 2016",1.2.1,4.1 and up,100000

In [52]:
playstore[playstore['Size'] == 'Varies with device']

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver,Installs_clean
37,Floor Plan Creator,ART_AND_DESIGN,4.1,36639,Varies with device,"5,000,000+",Free,0,Everyone,Art & Design,"July 14, 2018",Varies with device,2.3.3 and up,5000000
42,Textgram - write on photos,ART_AND_DESIGN,4.4,295221,Varies with device,"10,000,000+",Free,0,Everyone,Art & Design,"July 30, 2018",Varies with device,Varies with device,10000000
52,Used Cars and Trucks for Sale,AUTO_AND_VEHICLES,4.6,17057,Varies with device,"1,000,000+",Free,0,Everyone,Auto & Vehicles,"July 30, 2018",Varies with device,Varies with device,1000000
67,Ulysse Speedometer,AUTO_AND_VEHICLES,4.3,40211,Varies with device,"5,000,000+",Free,0,Everyone,Auto & Vehicles,"July 30, 2018",Varies with device,Varies with device,5000000
68,REPUVE,AUTO_AND_VEHICLES,3.9,356,Varies with device,"100,000+",Free,0,Everyone,Auto & Vehicles,"May 25, 2018",Varies with device,Varies with device,100000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10713,My Earthquake Alerts - US & Worldwide Earthquakes,WEATHER,4.4,3471,Varies with device,"100,000+",Free,0,Everyone,Weather,"July 24, 2018",Varies with device,Varies with device,100000
10725,Posta App,MAPS_AND_NAVIGATION,3.6,8,Varies with device,"1,000+",Free,0,Everyone,Maps & Navigation,"September 27, 2017",Varies with device,4.4 and up,1000
10765,Chat For Strangers - Video Chat,SOCIAL,3.4,622,Varies with device,"100,000+",Free,0,Mature 17+,Social,"May 23, 2018",Varies with device,Varies with device,100000
10826,Frim: get new friends on local chat rooms,SOCIAL,4.0,88486,Varies with device,"5,000,000+",Free,0,Mature 17+,Social,"March 23, 2018",Varies with device,Varies with device,5000000
10839,The SCP Foundation DB fr nn5n,BOOKS_AND_REFERENCE,4.5,114,Varies with device,"1,000+",Free,0,Mature 17+,Books & Reference,"January 19, 2015",Varies with device,Varies with device,1000

In [56]:
print(8823  + 312 + 1694)

10829

In [57]:
playstore.shape

(10829, 14)

let's keep the size column as it is for now

##### Price column str -> int

In [59]:
playstore['Price'].str.startswith('$').sum()

np.int64(797)

In [60]:
playstore['Price'].str.startswith('0').sum()

np.int64(10032)

In [61]:
print(797 + 10032)

10829

In [62]:
playstore['Price_clean'] = playstore['Price'].str.replace('$','')

In [64]:
playstore['Price_clean'].str.startswith('$').sum()

np.int64(0)

In [66]:
playstore['Price_clean'] = playstore['Price_clean'].astype(float)

In [67]:
playstore.dtypes

App                   str
Category              str
Rating            float64
Reviews               str
Size                  str
Installs              str
Type                  str
Price                 str
Content Rating        str
Genres                str
Last Updated          str
Current Ver           str
Android Ver           str
Installs_clean      int64
Price_clean       float64
dtype: object

In [72]:
playstore.sample(10)

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver,Installs_clean,Price_clean
9931,SK Bosnia Online EU Teplice,SPORTS,4.191838,2,10M,5+,Free,0,Everyone,Sports,"August 21, 2017",1.2,4.0 and up,5,0.00
4038,"DU Recorder – Screen Recorder, Video Editor, Live",VIDEO_PLAYERS,4.800000,2588730,9.7M,"50,000,000+",Free,0,Everyone,Video Players & Editors,"July 30, 2018",1.7.1.3,5.0 and up,50000000,0.00
8739,Find Fast Food,SHOPPING,3.300000,272,785k,"100,000+",Free,0,Everyone,Shopping,"November 11, 2012",1.1.6,2.2 and up,100000,0.00
6917,BW Ultra,PRODUCTIVITY,4.191838,0,24M,10+,Free,0,Everyone,Productivity,"July 3, 2018",1.0,4.0 and up,10,0.00
9801,OpenGL ES Extensions - The OpenGL Utility,TOOLS,4.200000,513,2.0M,"50,000+",Free,0,Everyone,Tools,"May 6, 2018",5.0.5,4.0 and up,50000,0.00
8736,FINAL FANTASY DIMENSIONS,FAMILY,4.300000,8450,1.1M,"100,000+",Paid,$13.99,Everyone,Role Playing,"March 15, 2017",1.1.3,2.3.3 and up,100000,13.99
3684,YouTube Studio,VIDEO_PLAYERS,4.300000,436921,Varies with device,"10,000,000+",Free,0,Teen,Video Players & Editors,"June 28, 2018",Varies with device,Varies with device,10000000,0.00
4802,Antivirus & Mobile Security,TOOLS,4.600000,351267,5.0M,"10,000,000+",Free,0,Everyone,Tools,"February 9, 2018",3.1.0,4.0 and up,10000000,0.00
3578,My baby Game (Balloon POP!),PARENTING,3.800000,3614,3.3M,"1,000,000+",Free,0,Everyone,Parenting;Brain Games,"May 28, 2018",2.15.2714,4.0 and up,1000000,0.00
6044,BD Live Call,COMMUNICATION,4.400000,7,308k,"5,000+",Free,0,Everyone,Communication,"September 6, 2016",1.01,2.0 and up,5000,0.00

##### Reviews column str -> int

In [73]:
playstore['Reviews_clean'] = playstore['Reviews'].astype(int)

In [74]:
playstore.dtypes

App                   str
Category              str
Rating            float64
Reviews               str
Size                  str
Installs              str
Type                  str
Price                 str
Content Rating        str
Genres                str
Last Updated          str
Current Ver           str
Android Ver           str
Installs_clean      int64
Price_clean       float64
Reviews_clean       int64
dtype: object

In [75]:
playstore.describe()

             Rating  Installs_clean   Price_clean  Reviews_clean
count  10829.000000    1.082900e+04  10829.000000   1.082900e+04
mean       4.191838    1.547990e+07      1.028091   4.446018e+05
std        0.479038    8.507114e+07     15.957778   2.929213e+06
min        1.000000    0.000000e+00      0.000000   0.000000e+00
25%        4.100000    5.000000e+03      0.000000   3.800000e+01
50%        4.200000    1.000000e+05      0.000000   2.100000e+03
75%        4.500000    5.000000e+06      0.000000   5.481500e+04
max        5.000000    1.000000e+09    400.000000   7.815831e+07

In [76]:
playstore.to_csv('new_googleplaystore.csv')

# Analysis