# Weekly Coffee Sales Analysis

This project analyzes weekly coffee sales data using Pandas.

The objectives are to:

- Explore the dataset
- Calculate total sales
- Analyze sales by coffee type
- Analyze daily sales performance
- Calculate revenue
- Compare weekday and weekend sales
- Measure sales target achievement

## Import Required Libraries

Import the libraries required for data analysis.

In [1]:
import pandas as pd

## Load Dataset

Read the coffee sales dataset into a Pandas DataFrame.

In [2]:
coffee = pd.read_csv("coffee.csv")

In [3]:
coffee

          Day Coffee Type  Units Sold
0      Monday    Espresso          25
1      Monday       Latte          15
2     Tuesday    Espresso          30
3     Tuesday       Latte          20
4   Wednesday    Espresso          35
5   Wednesday       Latte          25
6    Thursday    Espresso          40
7    Thursday       Latte          30
8      Friday    Espresso          45
9      Friday       Latte          35
10   Saturday    Espresso          45
11   Saturday       Latte          35
12     Sunday    Espresso          45
13     Sunday       Latte          35

## Dataset Overview

Display the dataset and inspect its structure.

In [4]:
coffee.shape

(14, 3)

- rows = 14
- columns = 3

In [5]:
coffee.columns

Index(['Day', 'Coffee Type', 'Units Sold'], dtype='str')

In [6]:
coffee.info()

<class 'pandas.DataFrame'>
RangeIndex: 14 entries, 0 to 13
Data columns (total 3 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Day          14 non-null     str
 1   Coffee Type  14 non-null     str
 2   Units Sold   14 non-null     int64
dtypes: int64(1), str(2)
memory usage: 468.0 bytes

In [7]:
coffee.dtypes

Day              str
Coffee Type      str
Units Sold     int64
dtype: object

## Total Sales Analysis

Calculate the total and average number of coffee units sold during the week.

In [8]:
# Total Units Sold
coffee["Units Sold"].sum()

np.int64(460)

In [9]:
# Average Units Sold
coffee["Units Sold"].mean()

np.float64(32.857142857142854)

## Coffee Type Analysis

Analyze sales performance by coffee type to determine which beverage generated the most sales.

In [10]:
coffee.groupby("Coffee Type")["Units Sold"].sum()

Coffee Type
Espresso    265
Latte       195
Name: Units Sold, dtype: int64

In [11]:
coffee.groupby("Coffee Type").agg({'Units Sold': 'sum'})

             Units Sold
Coffee Type
Espresso            265
Latte               195

## Daily Sales Analysis

Calculate total units sold per day and identify the best-performing sales day.

In [12]:
coffee.groupby("Day").agg({'Units Sold':'sum'})

           Units Sold
Day
Friday             80
Monday             40
Saturday           80
Sunday             80
Thursday           70
Tuesday            50
Wednesday          60

In [13]:
coffee.groupby("Day")["Units Sold"].sum()

Day
Friday       80
Monday       40
Saturday     80
Sunday       80
Thursday     70
Tuesday      50
Wednesday    60
Name: Units Sold, dtype: int64

## Best Sales Day

Sort daily sales in descending order to determine the highest-performing day.

In [14]:
coffee.groupby("Day")["Units Sold"].sum().sort_values(ascending=False)

Day
Friday       80
Saturday     80
Sunday       80
Thursday     70
Wednesday    60
Tuesday      50
Monday       40
Name: Units Sold, dtype: int64

In [15]:
coffee.groupby("Day").agg({'Units Sold':'sum'}).sort_values(
    by="Units Sold",
    ascending=False
)

           Units Sold
Day
Friday             80
Saturday           80
Sunday             80
Thursday           70
Wednesday          60
Tuesday            50
Monday             40

In [16]:
coffee.groupby(["Coffee Type"]).agg({'Units Sold':'sum'}).sort_values(
    by="Units Sold",
    ascending=False
)

             Units Sold
Coffee Type
Espresso            265
Latte               195

## High Volume Sales Records

Filter records where more than 30 units were sold.

In [17]:
coffee[coffee["Units Sold"] > 30]

          Day Coffee Type  Units Sold
4   Wednesday    Espresso          35
6    Thursday    Espresso          40
8      Friday    Espresso          45
9      Friday       Latte          35
10   Saturday    Espresso          45
11   Saturday       Latte          35
12     Sunday    Espresso          45
13     Sunday       Latte          35

## Revenue Calculation

Assign prices to each coffee type and calculate revenue for every transaction.

In [18]:
import numpy as np
coffee['Price'] = np.where(coffee['Coffee Type'] == 'Espresso',500,700)

In [19]:
coffee['Revenue'] = coffee['Units Sold'] * coffee['Price']

In [20]:
coffee

          Day Coffee Type  Units Sold  Price  Revenue
0      Monday    Espresso          25    500    12500
1      Monday       Latte          15    700    10500
2     Tuesday    Espresso          30    500    15000
3     Tuesday       Latte          20    700    14000
4   Wednesday    Espresso          35    500    17500
5   Wednesday       Latte          25    700    17500
6    Thursday    Espresso          40    500    20000
7    Thursday       Latte          30    700    21000
8      Friday    Espresso          45    500    22500
9      Friday       Latte          35    700    24500
10   Saturday    Espresso          45    500    22500
11   Saturday       Latte          35    700    24500
12     Sunday    Espresso          45    500    22500
13     Sunday       Latte          35    700    24500

## Revenue Analysis

Analyze total revenue and revenue distribution across coffee types and days.

In [21]:
coffee['Revenue'].sum()

np.int64(269000)

In [22]:
coffee.groupby('Coffee Type').agg({'Revenue':'sum'})

             Revenue
Coffee Type
Espresso      132500
Latte         136500

In [23]:
coffee.groupby('Day').agg({'Revenue':'sum'})

           Revenue
Day
Friday       47000
Monday       23000
Saturday     47000
Sunday       47000
Thursday     41000
Tuesday      29000
Wednesday    35000

## Weekend vs Weekday Analysis

Classify records as weekday or weekend sales and compare total units sold.

In [24]:
weekend = ((coffee['Day']=='Saturday') | (coffee['Day']=='Sunday') )

coffee["Type"] = np.where(weekend,'Weekend','Weekday')

In [25]:
coffee

          Day Coffee Type  Units Sold  Price  Revenue     Type
0      Monday    Espresso          25    500    12500  Weekday
1      Monday       Latte          15    700    10500  Weekday
2     Tuesday    Espresso          30    500    15000  Weekday
3     Tuesday       Latte          20    700    14000  Weekday
4   Wednesday    Espresso          35    500    17500  Weekday
5   Wednesday       Latte          25    700    17500  Weekday
6    Thursday    Espresso          40    500    20000  Weekday
7    Thursday       Latte          30    700    21000  Weekday
8      Friday    Espresso          45    500    22500  Weekday
9      Friday       Latte          35    700    24500  Weekday
10   Saturday    Espresso          45    500    22500  Weekend
11   Saturday       Latte          35    700    24500  Weekend
12     Sunday    Espresso          45    500    22500  Weekend
13     Sunday       Latte          35    700    24500  Weekend

In [26]:
coffee.groupby("Type")["Units Sold"].sum()

Type
Weekday    300
Weekend    160
Name: Units Sold, dtype: int64

## Sales Target Achievement

Determine whether each sales record achieved the target of more than 30 units sold.

In [27]:
coffee['Target Met'] = np.where(coffee['Units Sold'] > 30 , 'Yes', 'No')

In [28]:
coffee

          Day Coffee Type  Units Sold  Price  Revenue     Type Target Met
0      Monday    Espresso          25    500    12500  Weekday         No
1      Monday       Latte          15    700    10500  Weekday         No
2     Tuesday    Espresso          30    500    15000  Weekday         No
3     Tuesday       Latte          20    700    14000  Weekday         No
4   Wednesday    Espresso          35    500    17500  Weekday        Yes
5   Wednesday       Latte          25    700    17500  Weekday         No
6    Thursday    Espresso          40    500    20000  Weekday        Yes
7    Thursday       Latte          30    700    21000  Weekday         No
8      Friday    Espresso          45    500    22500  Weekday        Yes
9      Friday       Latte          35    700    24500  Weekday        Yes
10   Saturday    Espresso          45    500    22500  Weekend        Yes
11   Saturday       Latte          35    700    24500  Weekend        Yes
12     Sunday    Espresso          45    500    22500  Weekend        Yes
13     Sunday       Latte          35    700    24500  Weekend        Yes

## Revenue Contribution Analysis

Calculate the percentage contribution of each coffee type to total revenue.

In [29]:
v = coffee['Revenue'].sum()

coffee.groupby('Coffee Type')['Revenue'].sum() / v * 100

Coffee Type
Espresso    49.256506
Latte       50.743494
Name: Revenue, dtype: float64

## Export Summary Report

Generate and export a summary report for future analysis.

In [30]:
summary = coffee.groupby("Coffee Type").agg({
    "Units Sold": "sum",
    "Revenue": "sum"
})

summary.to_csv("weekly_coffee_report.csv")

# Conclusion

Key Findings:

- Total weekly coffee sales were successfully calculated.
- Sales were analyzed by coffee type and by day.
- Revenue was calculated using product pricing.
- Weekend and weekday performance were compared.
- Sales target achievement was measured.
- Revenue contribution percentages were determined.
- A summary report was exported for reporting purposes.

This project demonstrates fundamental Pandas operations including data loading, filtering, grouping, aggregation, sorting, column creation, and exporting results.